name: Deploy to Production

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Prepare deployment folder
        run: |
          mkdir deploy-dir
          cp -r .next public package.json package-lock.json server.js next.config.ts deploy-dir/ || true

      - name: Switch to production branch (create if needed)
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git fetch origin production || true
      
          if git ls-remote --exit-code --heads origin production; then
            git checkout -B production origin/production
          else
            git switch --orphan production
            git rm -rf . || true
          fi

      - name: Clear old contents and copy new
        run: |
          find . -mindepth 1 -maxdepth 1 ! -name 'deploy-dir' ! -name '.git' -exec rm -rf {} +
          cp -r deploy-dir/. .
          rm -rf deploy-dir

      - name: Commit and push to production (manual git)a
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          MAIN_COMMIT=$(git rev-parse origin/main)
          COMMIT_URL="https://github.com/${{ github.repository }}/commit/$MAIN_COMMIT"
          COMMIT_MSG="Deploy to production - based on main commit: $COMMIT_URL"
          git commit -m "$COMMIT_MSG" || echo "Nothing to commit"
          git push origin production
